language: python
python:
  - "3.7"

addons:
  chrome: stable

before_install:
  # starting a GUI to run tests, per https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

# command to install dependencies
install:
  - "pip install -r requirements.txt"
# command to run tests
script: pytest

notifications:  
  email:  
    recipients:  
    - brunsergiog@gmail.com 
    on_success: always  
    on_failure: always
