language: python
python:
  - "3.7"

# command to install dependencies
install:
  - "pip install -r requirements.txt"
# command to run tests
script: pytest

notifications:  
  email:  
    recipients:  
    - brunsergiog@gmail.com 
    on_success: always  
    on_failure: always
